
package de.xdevsoftware.rapidclipse.demo.image.upload.ui;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;

import javax.servlet.ServletContext;

import com.vaadin.server.FileResource;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.Notification;
import com.vaadin.ui.Notification.Type;
import com.vaadin.ui.Upload.Receiver;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Upload.SucceededListener;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevImage;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevUpload;
import com.xdev.ui.XdevView;

public class MainView extends XdevView {

	public MainView() {
		super();
		this.initUI();

		final ImageUploader uploader = new ImageUploader();
		//Receiver for the upload component
		this.upload.setReceiver(uploader);
		//SucceededListener for the upload component.
		this.upload.addSucceededListener(uploader);
	}

	class ImageUploader implements Receiver, SucceededListener {

		public File file;

		@Override
		public void uploadSucceeded(final SucceededEvent event) {

			//Sets the uploaded file into the image component.
			MainView.this.image.setSource(new FileResource(this.file));

		}

		@Override
		public OutputStream receiveUpload(final String filename, final String mimeType) {

			FileOutputStream fos = null;

			try {
				// Get path to servlet's temp directory
				final File temporaryDirectory = (File) VaadinServlet.getCurrent().getServletContext()
						.getAttribute(ServletContext.TEMPDIR);
				// Concatenate temporaryDirectory with filename and open the
				// file for writing.
				this.file = new File(temporaryDirectory, filename);
				// Create the output stream
				fos = new FileOutputStream(this.file);

			} catch (final Exception e) {
				Notification.show("Could not open file!", Type.ERROR_MESSAGE);
				return null;
			}

			return fos;
		}

	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.upload = new XdevUpload();
		this.panel = new XdevPanel();
		this.image = new XdevImage();

		this.upload.setImmediate(true);

		this.image.setSizeUndefined();
		this.panel.setContent(this.image);
		this.gridLayout.setColumns(1);
		this.gridLayout.setRows(2);
		this.upload.setSizeUndefined();
		this.gridLayout.addComponent(this.upload, 0, 0);
		this.panel.setSizeFull();
		this.gridLayout.addComponent(this.panel, 0, 1);
		this.gridLayout.setColumnExpandRatio(0, 10.0F);
		this.gridLayout.setRowExpandRatio(1, 10.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	public XdevUpload upload;
	public XdevImage image;
	public XdevPanel panel;
	public XdevGridLayout gridLayout;
	// </generated-code>

}
